### ISSUE TITLE
Liquid error: Could not find asset snippets/style-bundle.liquid

### ISSUE THREAD

**Issue by GarrettWeinberg** [krjo/shopify-webpack-dev-workflow#16]
Im kinda new here, so i may be doing something wrong.
i added header.liquid in sections and i included it in theme.liquid `{% section 'header' %}` 
when i save i get this error on the page 

Liquid error: Could not find asset snippets/style-bundle.liquid
Liquid error: Could not find asset snippets/script-bundle.liquid

not sure if there is anything specific to do. I did see in the readme that new templates need the bundle.js file to be created, but nothing about sections. A push in the right direction would be helpful.

**Comment by krjo** [comment]
Hey Garrett, are you starting with this repo or are you trying to migrate an existing theme? Sounds like you just need to create those two snippets, and copy their liquid from this repo. Also a reminder, if you add a new template file, (ie. template-name.liquid, template-name.js, and template-name.scss), you'll need to restart npm/yarn to get webpack to recognize the new bundle entry file (the template-name.js). Happy to take a look if you wanna add me to your repo.

**Comment by GarrettWeinberg** [comment]
Hey im starting with this repo. cloned this, ran yarn, then tried to add the header.liquid. 
here is a link to the repo. https://github.com/GarrettWeinberg/shopify

**Comment by krjo** [comment]
You have both of those snippets in src and dist so you shouldn't be seeing liquid errors. Try running yarn deploy to make sure your theme is updated.

**Comment by GarrettWeinberg** [comment]
that worked. thanks for the help. not sure why it needed to deploy, but im finding shopify is a strange beast. Anyways, closing this issue. thanks again!
