### ISSUE TITLE
Where to add app-provided asset files

### ISSUE THREAD

**Issue by baronmunchowsen** [krjo/shopify-webpack-dev-workflow#17]
Often 3rd party Shopify apps will add files to the assets directory (e.g. css files).
Ideally these will can be added to the development repository to track the code and ensure that they don't get lost in a deploy.
Is there a place that these assets can be added in the /src/styles directory such that they would be copied 1-1 into the /dist/assets/ directory?

Thanks

**Comment by krjo** [comment]
Sure, I just added a vendor directory to src/assets with example files. I would keep src/styles for your theme files. You can add / update any subdirectories into src/assets/* and they will build into dist/assets.

**Comment by baronmunchowsen** [comment]
OK thanks - I was looking in the wrong place. It's obvious now!
