### ISSUE TITLE
Any chance HMR and devServer functionality could be added to this?

### ISSUE THREAD

**Issue by adrianocr** [krjo/shopify-webpack-dev-workflow#26]
HMR enables things like react fast refresh, and webpack's devServer functionality injects style changes directly into the document so that a browser refresh isn't necessary. Currently after any JS and/or CSS updates a full refresh of the page is necessary. 

Shopify's deprecated Slate tools does it for example.

**Comment by krjo** [comment]
I don't have any plans to add this. I found that process to be super cumbersome and annoying with Slate, and not all that helpful. Also made it a lot harder to share preview links.
