### ISSUE TITLE
npm run start

### ISSUE THREAD

**Issue by nikolay-gavrilov** [krjo/shopify-webpack-dev-workflow#30]
Hey! I get an error when starting the process. Where to look for the reason?) Thank you!

`PS D:\work\test_new_shopify_theme> npm run start

> shopify-webpack-theme-development@1.0.0 start
> NODE_ENV=development webpack --watch

Executing pre-build scripts
Webpack build in progress...🛠
(node:10044) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
(Use `node --trace-deprecation ...` to show where the warning was created)
Executing post-build scripts
webpack compiled successfully
Build Complete 📦
[development] opening https://omgstores.myshopify.com?preview_theme_id=22625884221
[development] Error while fetching info from server: requested theme was not found

D:\work\test_new_shopify_theme\node_modules\webpack-shell-plugin-next\lib\index.js:298
                throw error;
                ^
1
(Use `node --trace-uncaught ...` to show where the exception was thrown)
Note: This command was run via npm module 'win-node-env'
PS D:\work\test_new_shopify_theme>         `

**Comment by NexPB** [comment]
```
[development] opening https://omgstores.myshopify.com?preview_theme_id=22625884221
[development] Error while fetching info from server: requested theme was not found
```

Are you sure the theme id is correct?
