### ISSUE TITLE
css variables

### ISSUE THREAD

**Issue by zachinscho** [krjo/shopify-webpack-dev-workflow#6]
Any possibility to add the ability to add a variables.scss file somewhere and setup in the webpack config?

Webpack newb here, any help figuring that out would be much appreciated. Thank you!

**Comment by krjo** [comment]
Hey, you can definitely do this. The styles/ folder in the base theme might be misleading but you can add any folders you want in there. For example, my styles/ directory looks like this:

Partials are all imported into the layout & template scss files, which are imported into the JS bundle files. Hope this helps.

`
+ styles
  --+ components
    -- partial.scss
    -- partial.scss
  --+ global
    -- partial.scss
    -- partial.scss
  --+ helpers
    -- partial.scss
    -- partial.scss
  --+ layout
    -- theme.scss
    -- checkout.scss
  --+ sections
    -- partial.scss
    -- partial.scss
  --+ templates
    --+ article.scss
    --+ blog.scss
    --+ collection.scss
    --+ index.scss
    --+ product.scss
    --+ etc.
  --+ vendor
    -- partial.scss
    -- partial.scss  
`

**Comment by zachinscho** [comment]
Thanks for the reply @krjo! I've added my variables.scss file in the styles folder but getting 'Module build failed' SassError: Undefined variable: "$white" which is a color variable I've declared in my variables file. Any ideas? Do I need to adjust webpack.config.js at all to factor in the variables file somehow?

**Comment by krjo** [comment]
Are you importing your variables file into your template.scss file? 

ie. in product.scss 
```
@import '../helpers/variables';

h1 { color: $white; }

**Comment by krjo** [comment]
I just [made a commit](https://github.com/krjo/shopify-webpack-dev-workflow/commit/b54a4c513616d10bdbb972599c5ee225c0f104cb) with an example in the theme files in this repo.

**Comment by zachinscho** [comment]
Thanks @krjo I got that working! Might be nice in the future to use something like [sass-resources-loader](https://github.com/shakacode/sass-resources-loader) rather than having to @import in every file. But again - webpack newb here, I haven't been able to get that working yet. Thanks so much for your help!

**Comment by krjo** [comment]
Never heard of it but i'll check that out. Glad you got it working.
