### ISSUE TITLE
Node 12+ and latest themekit version

### ISSUE THREAD

**Issue by ianhoyte** [krjo/shopify-webpack-dev-workflow#7]
Great repo here, saved me a ton of time.

To get this working on node 12+ I had to update sass-loader to the latest version (10.0.4). While I was there I updated themekit to 1.1.6 as well, which appears to now need a flag on the watch command if you're now editing a live theme.

In webpack.config.js:

`scripts: ['echo Build Complete 📦','shopify-themekit watch --allow-live','shopify-themekit open'],`

**Comment by krjo** [comment]
Thanks for the note.
