### ISSUE TITLE
Clarify licensing of code

### ISSUE THREAD

**Issue by Perni1984** [krjo/shopify-webpack-dev-workflow#9]
Hi @krjo,

we are a holocratic organized software development company and are using shopify ourselves for some of our clients. We are looking into several solutions of how to modernize our development workflow for shopify and found your solution. Unfortunately I have nowhere found any indication about he license you released your code under. Could you kindly clarify this?

Thanks!

Christoph

**Comment by krjo** [comment]
Hi Christoph,

I updated the license from ISC to MIT. Both of these are standard open source licenses, more info here:

https://opensource.org/licenses/MIT
https://opensource.org/licenses/ISC
